[package]
name = "TwistedElGamal_Non-Interactive_Schnorr_Chaum-Pedersen_toolkit"
version = "0.1.0"
edition = "2024"

[dependencies]
curve25519-dalek = { version = "4.1.3", features = ["rand_core", "digest"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
